# Generated by Django 3.0.8 on 2020-07-14 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='body',
            field=models.TextField(default='Stock answer.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='faved_by',
            field=models.ManyToManyField(blank=True, related_name='a_faves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='faved_by',
            field=models.ManyToManyField(blank=True, related_name='q_faves', to=settings.AUTH_USER_MODEL),
        ),
    ]
